services:
  recall-backend:
    image: project-api
    build:
      context: .
      dockerfile: Dockerfile
    container_name: project-backend
    environment:
      - DB_HOST=project-postgres
      - DB_PORT=5432
      - DB_USER=project
      - DB_PASSWORD=tradiapassword
      - DB_NAME=tradiadb
    ports:
      - "8080:8080"
    depends_on:
      - project-postgres
    networks:
      - project-net

  recall-postgres:
    image: postgres:15
    container_name: project-postgres
    environment:
      - POSTGRES_USER=youruser
      - POSTGRES_PASSWORD=yourpassword
      - POSTGRES_DB=yourdb
    ports:
      - "5432:5432"
    networks:
      - recall-net

networks:
  recall-net:
    driver: bridge
