// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	dto "showtime-backend/internal/dto"

	mock "github.com/stretchr/testify/mock"
)

// IExampleService is an autogenerated mock type for the IExampleService type
type IExampleService struct {
	mock.Mock
}

// CreateExample provides a mock function with given fields: ctx, req
func (_m *IExampleService) CreateExample(ctx context.Context, req dto.InviteRequest) error {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateExample")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.InviteRequest) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewIExampleService creates a new instance of IExampleService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIExampleService(t interface {
	mock.TestingT
	Cleanup(func())
}) *IExampleService {
	mock := &IExampleService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
